### ISSUE TITLE
peer-to-peer code reviews

### ISSUE THREAD

**Issue by IamYunusAli** [MxoDevops/My-portfolio-microverse#4]
hey there @MxoDevops 
correct issues under their 
- Use Proper commenting on what you do 
- User Better semantic HTML.

```
<article>
        <h1>Hi I'm Thokozani<br />Glad to see you!</h1>
        <p class="paragraph-1">
          I’m a software developer! I can help you build a product , feature or
          website Look through some of my work and experience! If you like what
          you see and have a project you need to be coded, don’t hesitate to contact
          me.
        </p>
 </article>
```

**Comment by Nedramrez** [comment]
I kindly suggest not to use spaces in the names of images. It's better to use hyphens. Additional information is [here](https://uploadcare.com/blog/how-to-name-images-for-seo-step-by-step/).
